server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carrentalsys?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Colombo
    username: root
    password: 1313
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
